- name: Download repository
  get_url: url={{url}}/{{rpm}} dest=/root/{{rpm}}
  when: ansible_os_family == "RedHat"
  tags:
    - packages

- name: Install repository
  command: yum -y localinstall /root/{{rpm}}
  when: ansible_os_family == "RedHat"
  tags:
    - packages
    - repo

- name: Install Ajenti packages
  yum: name={{item}}
       state=installed
  with_items:
    - ajenti
  when: ansible_os_family == "RedHat"
  tags:
    - packages
