#
# https://docs.newrelic.com/docs/server/server-monitor-installation-redhat-and-centos
#
- name: Download newrlic repo
  get_url: url={{url}}/{{rpm}} dest=/root
  when: ansible_os_family == "RedHat"
  tags:
    - packages

- name: Install newrelic repo
  command: yum -y localinstall /root/{{rpm}}
  when: ansible_os_family == "RedHat"
  tags:
    - packages

- name: Install newrelic
  yum: name=newrelic-sysmond
       state=installed
  when: ansible_os_family == "RedHat"
  tags:
    - packages

- name: Set license key
  command: nrsysmond-config --set license_key={{license_key}}
  tags:
    - license

- name: Restart newrelic monitor
  service: name=newrelic-sysmond
           state=restarted
  tags:
    - services
