
- name: Install /etc/hosts
  template: src={{ansible_os_family}}.hosts.j2
            dest=/etc/hosts
            owner=root
            group=root
            mode=0644
            backup=yes
  tags:
    - hosts

- name: Set hostname for Debian
  copy: dest=/etc/hostname
        content="{{inventory_hostname}}"
  when: ansible_os_family == "Debian"
  tags:
    - hostname

- name: Set hostname
  lineinfile: dest=/etc/sysconfig/network
              regexp='^HOSTNAME'
              line="HOSTNAME={{inventory_hostname}}"
  when: ansible_os_family == "RedHat"
  tags:
    - hostname
