#
# Shorewall firewall ipset blacklist
#
# http://www.ipdeny.com/blog/blocking-country-ip-tables-using-our-data-blocks-and-ipset-utility/
# http://shorewall.net/blacklisting_support.htm
# http://www.shorewall.net/ipsets.html
#
# http://braindump.mrzesty.net/68.html
#
#
    - name: Install ipset packages
      yum: name={{item}}
           state=installed
      with_items:
        - ipset
      when: ansible_os_family == "RedHat"
      tags:
        - packages

### CONFIGURATION
    - name: Create /etc/ipset.d
      file: path=/etc/ipset.d
            owner=root
            group=root
            state=directory
      tags:
        - config
        - directories

    - name: Install ipset tables
      template: src={{item}}.j2
                dest=/etc/ipset.d/{{item}}
                owner=root
                group=root
                mode=0755
      with_items:
        - functions
        - whitelist.ipset
      tags:
        - config

#    - name: Disable SAVE_IPSETS
#      lineinfile: dest=/etc/shorewall/shorewall.conf
#                  regexp='^SAVE_IPSETS='
#                  line='SAVE_IPSETS=No'
#      tags:
#        - config
#    - name: Disable DYNAMIC_BLACKLIST
#      lineinfile: dest=/etc/shorewall/shorewall.conf
#                  regexp='^DYNAMIC_BLACKLIST='
#                  line='DYNAMIC_BLACKLIST=Yes'
#      tags:
#        - config

    - name: Install ipset service
      template: src=ipset.j2
                dest=/etc/init.d/ipset
                owner=root
                group=root
                mode=0755
      tags:
        - config

    - name: Start ipset
      service: name=ipset
               state=reloaded
               enabled=yes
