
- name: Install packages
  yum: name={{item}}
       state=installed
  with_items:
    - openvpn
  when: ansible_os_family == "RedHat"
  tags:
    - packages


### CERTIFICATES
- name: Install /etc/openvpn/ca.crt
  copy: src=ca/{{openvpn.ca}}/{{openvpn.ver}}/keys/ca.crt
        dest=/etc/openvpn/ca.crt
        owner=root
        group=root
        mode=0644
  tags:
    - ca
    - config

- name: Install /etc/openvpn/dh2048.pem
  copy: src=ca/{{openvpn.ca}}/{{openvpn.ver}}/keys/dh2048.pem
        dest=/etc/openvpn/dh2048.pem
        owner=root
        group=root
        mode=0644
  tags:
    - dh
    - config

- name: Install /etc/openvpn/ta.key
  copy: src=ca/{{openvpn.ca}}/{{openvpn.ver}}/keys/ta.key
        dest=/etc/openvpn/ta.key
        owner=root
        group=root
        mode=0600
  tags:
    - ta
    - config

- name: Install /etc/openvpn/server.crt
  copy: src=ca/{{openvpn.ca}}/{{openvpn.ver}}/keys/{{inventory_hostname}}.crt
        dest=/etc/openvpn/server.crt
        owner=root
        group=root
        mode=0644
  tags:
    - cert
    - config

- name: Install /etc/openvpn/server.key
  copy: src=ca/{{openvpn.ca}}/{{openvpn.ver}}/keys/{{inventory_hostname}}.key
        dest=/etc/openvpn/server.key
        owner=root
        group=root
        mode=0600
  tags:
    - key
    - config


### FIREWALL
- name: Install ipset tables
  template: src={{item}}.j2
            dest=/etc/ipset.d/{{item}}
            owner=root
            group=root
            mode=0755
  with_items:
    - openvpn.ipset
  tags:
    - ipset
  notify:
    - Restart ipset


- name: Install firewall rules
  template: src=rule-openvpn.j2
            dest=/etc/shorewall/rules.d/openvpn
            owner=root
            group=root
            mode=0640
  tags:
    - firewall
  notify:
  - Restart shorewall


#### CONFIGURATION
- name: Install ipset tables
  template: src=server.conf.j2
            dest=/etc/openvpn/server.conf
            owner=root
            group=root
            mode=0644
  tags:
    - config
  notify:
    - Restart openvpn

- name: Start openvpn
  service: name=openvpn
           state=started
           enabled=yes
